@startuml
title Model-View-Controller Pattern for Plan Manifestation

' ============================================================================
' Define packages in left-to-right order
' ============================================================================

left to right direction
skinparam packageStyle rectangle

package "Model" as ModelPkg {
  top to bottom direction
  class "Unstructured Data" as UnstructuredData
  class "Record Data" as RecordData
  class "Structured Data" as StructuredData
  class "Curated Plan Data" as CuratedPlanData
  class "Change and\nReconciliation Data" as ChangeData
  class "Clinician Assertions\nof Plan Inclusion" as ClinicianAssertions
  UnstructuredData -[hidden]-> RecordData
  RecordData -[hidden]-> StructuredData
  StructuredData -[hidden]-> CuratedPlanData
  CuratedPlanData -[hidden]-> ChangeData
  ChangeData -[hidden]-> ClinicianAssertions
}

package "View" as ViewPkg {
  top to bottom direction
  class "SOAP note" as SOAPNote
  class "Plan Document\n(generated)" as PlanDocGenerated
  class "UI Plan View" as UIPlanView
  class "API Plan Payload" as APIPlanPayload
  class "Plan Document\n(curated)" as PlanDocCurated
  SOAPNote -[hidden]-> PlanDocGenerated 
  PlanDocGenerated -[hidden]-> UIPlanView
  UIPlanView -[hidden]-> APIPlanPayload
  APIPlanPayload -[hidden]->  PlanDocCurated
}
package "Controller" as ControllerPkg {
  top to bottom direction
  class "Human Intent" as HumanIntent
  class "Document Specification" as DocumentSpec
  class "UI Software Rules" as UISoftwareRules
  class "Payload Specification" as PayloadSpec
  class "Guideline" as Guideline
  HumanIntent -[hidden]-> DocumentSpec
  DocumentSpec -[hidden]-> UISoftwareRules
  UISoftwareRules -[hidden]-> PayloadSpec
  PayloadSpec -[hidden]-> Guideline
}

' ============================================================================
' Assert layout tweaks
' ============================================================================

  UnstructuredData -[hidden]left-> SOAPNote
  HumanIntent -[hidden]right-> SOAPNote
  CuratedPlanData -[hidden]left-> Guideline
  Guideline -[hidden]right-> PlanDocCurated

' ============================================================================
' Assert class relationships
' ============================================================================
  StructuredData --|> RecordData
  UnstructuredData --|> RecordData
  CuratedPlanData --|> StructuredData
  ChangeData --* CuratedPlanData
  ClinicianAssertions --* CuratedPlanData

  HumanIntent --> SOAPNote : controls
  UnstructuredData --> SOAPNote : generates
  UISoftwareRules --> UIPlanView : controls
  StructuredData --> UIPlanView : generates
  DocumentSpec --> PlanDocGenerated : controls
  StructuredData --> PlanDocGenerated : generates
  PayloadSpec --> APIPlanPayload : controls
  StructuredData --> APIPlanPayload : generates
  Guideline --> CuratedPlanData : contributes
  CuratedPlanData --> PlanDocCurated : generates
@enduml